# vim: se filetype=yaml.ansible
---

- hosts: all
  vars_files:
    - vars.yml

  tasks:

    - name: "Check if Firefox is already installed"
      register: installed_check
      stat:
        path: "{{ install_dir }}"

    - name: "Download Firefox-Dev release"
      when: installed_check.stat.exists == False
      register: ff_download
      get_url:
        url: "{{ download_url }}"
        dest: "/tmp/ffd.tar.bz2"

    - name: "Unpack Firefox"
      become: true
      when: ff_download.changed
      unarchive:
        dest: "{{ install_base }}"
        remote_src: true
        src: "/tmp/ffd.tar.bz2"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Rename extracted files"
      become: true
      command: "mv {{ install_base }}/firefox {{ install_dir }}"
      when: ff_download.changed

    - name: "Symlink Firefox to system PATH"
      become: true
      file:
        src: "{{ install_dir }}/firefox"
        dest: "{{ install_target }}"
        state: link

    - name: "Symlink Desktop entry"
      register: desktop_target
      become: true
      file:
        src: "{{ repo_dir }}/firefox-developer.desktop"
        dest: "{{ desktop_target }}"
        state: link

    - name: "Set default browser for user"
      when: desktop_target.changed
      become: true
      become_user: "{{ user }}"
      command: "xdg-settings set default-web-browser firefox-developer.desktop"



