---

# Play to configure the various tools I use on a regular basis

- hosts: all
  vars_files:
    - vars.yml

  tasks:
      - name: Setup mosh
        apt:
          name: mosh
          cache_valid_time: 600
        become: yes

