---
global:
  # Send anonymous usage data
  sendAnonymousUsage: true

providers:
  docker: {}
  file:
    directory: /etc/traefik/dynamic

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: secweb
          scheme: https

  secweb:
    address: :443

api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: DEBUG
accessLog: {}

certificatesResolvers:
  internal:
    acme:
      email: sammartin@hey.com
      caServer: https://laptop-server.home:8443/acme/acme/directory
      storage: /acme.json
      certificatesDuration: 24
      #tlsChallenge: {}

      httpChallenge:
        entryPoint: web
