---
# Variables used when setting up tools
user: "{{ansible_user_id}}"

dotfiles_base_dir: "{{personal_code_base_dir}}/dotfiles/dotfiles"
personal_code_base_dir: "/home/{{user}}/code/personal"
python_bin_dir: "/home/{{user}}/.local/bin"

default_python_version: "3.8.2"
python_versions:
  - "{{default_python_version}}"

# Note, first is the package to install, second is the executable to check for!
python_tools:
  - [["ansible", "ansible"]]
  - [["glances", "glances"]]
  - [["hatch", "hatch"]]
  - [["pipenv", "pipenv"]]
  - [["powerline-status", "powerline"]]
    #- [["powerline-gitstatus", "powerline-gitstatus"]]
  - [["yamllint", "yamllint"]]
  - [["yq", "yq"]]
