---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # - name: arch
  #   image: "archimg/base-devel"
  #   image_version: "latest"
  - name: bionic
    image: "ubuntu"
    image_version: "bionic"
  - name: xenial
    image: "ubuntu"
    image_version: "xenial"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # Disabled as the role currently wil always run an update on installed modules...
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
