# Molecule managed

FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates acl && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v pacman) ]; then pacman --noconfirm -Syu python2 && ln -sf /usr/bin/python2 /usr/bin/python; fi;

RUN getent group sudo || groupadd sudo

{% if 'ubuntu' in item.image | lower %}
RUN sed -i 's/%sudo\sALL=(ALL:ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
{% else %}
RUN sed -i 's/# %sudo\sALL=(ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
{% endif %}

RUN useradd -d /home/tmp -m tmp
RUN usermod -a -G sudo tmp

{% if 'ubuntu' not in item.image | lower %}
RUN sed -i s/#en_US.UTF-8/en_US.UTF-8/ /etc/locale.gen && locale-gen
{% endif %}

USER tmp
