#!/usr/bin/zsh
# This file is called by all interactive shells (i.e. anything except scripts etc.)

# # Profiling ZSH
# zmodload zsh/zprof

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' max-errors 8
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/sam/.zshrc'
fpath+=~/.zfunc

autoload -Uz compinit
fpath+=~/.config/zsh_completions
fpath+=~/.zsh/completion

if [ $(date +'%s') != $(stat -c '%Y' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt appendhistory autocd extendedglob notify
bindkey -v
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.

# Allow ZSH to treat # characters like comments when used on the command line.
# For some reason, this isn't default behaviour.
setopt interactivecomments

# Allow vim-like autocompletion of history
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward


# Source aliases
source "$HOME/.config/nixpkgs/dotfiles/zsh/aliases.zsh"

# Source Environment settings
source "$HOME/.config/nixpkgs/dotfiles/zsh/envs.zsh"

# Source Extra Key bindings
source "$HOME/.config/nixpkgs/dotfiles/zsh/keys.zsh"

# Source SSH-Agent Management tooling
source "$HOME/.config/nixpkgs/dotfiles/zsh/ssh_agent.zsh"

# Begin loading of zplug plugins etc.
source "$HOME/.config/zplug/init.zsh"
#
# Source ZPlug definitions
source "$HOME/.config/nixpkgs/dotfiles/zsh/zplug.zsh"

# zplug check returns true if all packages are installed
# Therefore, when it returns false, run zplug install
if ! zplug check; then
    zplug install
fi

# MUST BE AT THE BOTTOM!!
# Load all plugins
zplug load
