# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' max-errors 8
zstyle :compinstall filename '/home/sam/.zshrc'

autoload -Uz compinit
fpath+=~/.config/zsh_completions
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
setopt appendhistory autocd extendedglob notify
bindkey -v
# End of lines configured by zsh-newuser-install

# Allow ZSH to treat # characters like comments when used on the command line.
# For some reason, this isn't default behaviour.
setopt interactivecomments

# Allow vim-like autocompletion of history
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward


# Source aliases
source ~/code/personal/dotfiles/zsh/aliases.zsh

# Source Environment settings
source ~/code/personal/dotfiles/zsh/envs.zsh

# Source Extra Key bindings
source ~/code/personal/dotfiles/zsh/keys.zsh

# Source SSH-Agent Management tooling
source ~/code/personal/dotfiles/zsh/ssh_agent.zsh

# Begin loading of zplug plugins etc.
source ~/.config/zplug/init.zsh
#
# Source ZPlug definitions
source ~/code/personal/dotfiles/zsh/zplug.zsh

# zplug check returns true if all packages are installed
# Therefore, when it returns false, run zplug install
if ! zplug check; then
    zplug install
fi

# MUST BE AT THE BOTTOM!!
# Load all plugins
zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
