---
- name: Import OS specific vars
  include_vars: "{{ansible_os_family|lower()|default(omit)}}.yml"

- name: "Install various programs needed for i3 operation"
  package:
    name: "{{ installs }}"
    state: present
  become: true

- name: Symlink i3 config into place
  file:
    src: "{{dotfiles_base_dir}}/i3"
    dest: "{{config_base_dir}}/i3"
    state: link
    force: true
    owner: "{{user}}"
    group: "{{user}}"
  become: true

- name: Symlink XResources file
  file:
    src: "{{dotfiles_base_dir}}/xresources/Xresources"
    dest: "/home/{{user}}/.Xresources"
    state: link
    force: true
    owner: "{{user}}"
    group: "{{user}}"
  become: true

- name: Generate i3 config for the target host
  template:
    # src: "{{dotfiles_base_dir}}/i3/base_config/config.j2"
    # dest: "{{config_base_dir}}/i3/config"
    src: "{{role_path}}/../../i3/base_config/config.j2"
    dest: "{{config_base_dir}}/i3/config"
    force: true
  become: true
  become_user: "{{user}}"

# TODO: Add installation of i3wm in a co-located playbook
# TODO: Add a playbook called workstation at dotfiles root which installs
#       everything i need for my nice workstation, including fonts, tools,
#       map in any themeing I want etc.
# TODO: Add logic here to determine what host the play is running on, and
#       compile the i3 config from machine specific and base configurations


# https://help.ubuntu.com/community/UbuntuStudio/UsbAudioDevices
